Final/Carrito/urls.py
from django.urls import path
from . import views

app_name = "carrito"

urlpatterns = [
    path("Agregar/<id>/", views.Agregar, name="Agregar"),
    path("Restar/<id>/", views.Restar, name="Restar"),
    path("Eliminar/<id>/", views.EliminarProducto, name="Eliminar"),
    path("Vaciar", views.Vaciar, name="Vaciar"),
]

Final/Final/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ProyectoFinal.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("Carrito/", include("Carrito.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final/ProyectoFinal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Home , name="Home"),
    path('AcercaDe', views.AcercaDe, name = "AcercaDe"),
    path('contacto', views.contacto, name = "contacto"),
    path('agregar', views.Agregar, name= "Agregar_Producto"),
    path('Lista', views.Lista, name= "Lista_Producto"),
    path('Editar/<id>/', views.Editar, name = "Editar_Producto"),
    path('Eliminar/<id>/', views.Eliminar, name = "Eliminar_Producto"),
    path('Registrarse', views.Registro , name = "Registro"),
    path('Filtro_de_categorias/<id>/', views.Filtro_Categorias, name="filtro_de_categorias"),
    path('VerProducto/<id>/', views.VerProducto, name = "VerProducto"),
    path('FiltroCategorias/<id>/', views.Filtro_Categorias, name = "FiltroCategorias"),
    path("Carrito", views.Carrito, name="Carrito"),
]

Final/Carrito/models.py
from django.db import models

# Create your models here.

Final/ProyectoFinal/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import PROTECT

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=50, null = False)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField(max_length= 411)
    categorias = models.ForeignKey(Categoria, null = True, on_delete= models.PROTECT)
    imagen = models.ImageField(upload_to="productos", null = True)

    def __str__(self):
        return self.nombre

Final/ProyectoFinal/forms.py
from django import forms
from django.forms import fields
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models


class AgregarForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = '__all__'

class RegistroForm(UserCreationForm):

    
    class Meta:
        model = User
        fields = [
            "email",
            "username",
            "password1",
            "password2",
        ]
        labels = {
            "email": "Correo Electronico",
            "username": "Nombre de usuario",
            "password1": "Contraseña",
            "password2": "Repetir contraseña",
        }

Final/Carrito/views.py
from ProyectoFinal.models import Producto
from django.shortcuts import render, redirect
from .carrito import Carrito
# Create your views here.

def Agregar(request, id):
    carrito = Carrito(request)
    producto = Producto.objects.get( id = id)
    carrito.AgregarCarrito(producto = producto)
    return redirect("Home")

def EliminarProducto(request, id):
    carrito = Carrito(request)
    producto = Producto.objects.get( id = id)
    carrito.Eliminar(producto = producto)
    return redirect("Home")

def Restar(request, id):
    carrito = Carrito(request)
    producto = Producto.objects.get( id = id)
    carrito.RestarUnidad(producto = producto)
    return redirect("Home")

def Vaciar(request):
    carrito = Carrito(request)
    carrito.VaciarCarrito()
    return redirect("Home")

Final/ProyectoFinal/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import render , redirect , get_object_or_404
from django.http import HttpResponse, request
from .models import Producto, Categoria
from .forms import AgregarForm, RegistroForm
from django.contrib  import messages
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.

def Home(request):
    
    productos = Producto.objects.all()
    data = {
        'productos': productos
    }
    return render(request, "plantillas/Home.html", data)

def AcercaDe(request):
    return render(request, "plantillas/AcercaDe.html")

def contacto(request):
    return render(request, "plantillas/contacto.html")
@permission_required('ProyectoFinal.add_producto')
def Agregar(request):
    data = {
        'form' : AgregarForm()
    }

    if request.method == 'POST':
        formulario = AgregarForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Agregado correctamente")
        else:
            data["form"] = formulario

    return render(request, "producto/agregar.html", data)
@permission_required('ProyectoFinal.view_producto')
def Lista(request):
    productos = Producto.objects.all()

    data = {
        'productos' : productos,
    }
    return render(request, 'producto/lista.html', data)
@permission_required('ProyectoFinal.change_producto')
def Editar(request, id):

    producto = get_object_or_404(Producto, id=id)

    data = {
        'form' : AgregarForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = AgregarForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Modificado correctamente")
            return redirect(to="Lista_Producto")
        else:
            data["form"] = formulario

    return render(request, 'producto/editar.html', data)
@permission_required('ProyectoFinal.delete_producto')
def Eliminar(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.success(request, "Eliminado Correctamente")
    return redirect(to = "Lista_Producto")

def Registro(request):

    data = {
        'form' : RegistroForm()
    }

    if request.method == 'POST':
        formulario = RegistroForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            return redirect(to='Home')
        data["form"] = formulario


    return render(request, 'registration/register.html', data)

def Filtro_Categorias(request, id):
    categoria = get_object_or_404(Categoria, id = id)
    producto = Producto.objects.all()
    producto = producto.filter(categoria = categoria)
    return render(request, 'plantillas/Home.html', {
        "lista_productos" : producto,
        "lista_categoria" : Categoria.objects.all(),
        "categoria_seleccionada" : categoria
    })

def VerProducto(request, id):
    producto = get_object_or_404(Producto, id = id)
    return render(request, 'producto/VerProducto.html',{
        "producto" : producto
    })

def Carrito(request):
    return render(request, 'plantillas/carrito.html')

Final/ProyectoFinal/templates/plantillas/AcercaDe.html
{% extends 'plantillas/layout.html' %}

{% block content %}

<div class = "InformacionEmpresa">
    <article>
        <h1>
            Acerca de JAGUARETE KAA S.A.
        </h1>
        <b>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates iste aperiam quam, quas perferendis,
            temporibus atque iure neque consequatur corrupti velit pariatur officia nam doloremque sunt deserunt quo a 
            tenetur!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates iste aperiam quam, quas perferendis,
            temporibus atque iure neque consequatur corrupti velit pariatur officia nam doloremque sunt deserunt quo a 
            tenetur!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates iste aperiam quam, quas perferendis,
            temporibus atque iure neque consequatur corrupti velit pariatur officia nam doloremque sunt deserunt quo a 
            tenetur!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates iste aperiam quam, quas perferendis,
            temporibus atque iure neque consequatur corrupti velit pariatur officia nam doloremque sunt deserunt quo a 
            tenetur!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates iste aperiam quam, quas perferendis,
            temporibus atque iure neque consequatur corrupti velit pariatur officia nam doloremque sunt deserunt quo a 
            tenetur! 
        </b>
    </article>
</div>

{% endblock %}

Final/ProyectoFinal/templates/plantillas/Carrito.html
{% extends 'plantillas/layout.html' %} 

{% block content %} 

<h1>{{user.username}}</h1>
<table class="table text-center">
    <thead>
      <tr>
        <th>Productos</th>
        <th>Cantidad</th>
        <th>Precio</th>
      </tr>
    </thead>
    <tbody>
        {% if request.session.carrito.items %}
            {% for key, value in request.session.carrito.items %}
                <tr class = "text-center">
                    <td>{{ value.nombre }} </td>
                    <td>{{ value.cantidad }} 
                        &nbsp;
                        &nbsp;
                        <a href ="{% url 'carrito:Restar' value.producto_id %}" class = "btn btn-success">-</a>
                    </td>
                    <td>{{ value.precio }} </td>
                </tr>
            {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">
                <div class="alert alert-danger text-center">
                    Sin productos
                </div>
            </td>
        </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="4">
                Total: {{SumaTotal}}
            </td>
        </tr>
    </tfoot>
  </table>
<div class="container">
    <a href = "#" class = "btn btn-success" style = "float:right;">Realizar Compra</a>
    <a href = "{% url 'carrito:Vaciar' %}" class = "btn btn-danger" style = "float:right;">Vaciar Carrito</a>
    
</div>
{% endblock %} 

Final/ProyectoFinal/templates/plantillas/Home.html
{% extends 'plantillas/layout.html' %}
{% load static %}

{% block content %}
{% load humanize %}

<br>
<h2 class = "titulo-producto">Productos</h2>
<br>
<div class="container">
    <div class="row">
        {% for p in productos %}
        <div class="col-8 col-md-2 offset-md-2">
            <div class="card" >
                {% if p.imagen %}
                <img src = "{{ p.imagen.url }}" class= "card-img-top" style="max-height: 100px;" alt = "imagen-producto">
                {% endif %}
                <div class = "card-body" style = "text-align: left; max-height: 100px;">
                    <h5>{{ p.categorias }}</h5>
                    <h3>{{ p.nombre }} </h3>
                </div>
                <br>
                <div class = "card-footer" style="max-height: 40px;">
                    <h3>${{ p.precio | intcomma}} </h3>
                </div>
                
                <div class = "card-footer" style="text-align: center;">
                    <a href = "{% url 'VerProducto' p.id %}" class= "btn btn-success">Ver Producto</a>
                </div>
            </div>
        </div>   
        {% endfor %}    
    </div>
</div>


{% endblock %}

Final/ProyectoFinal/templates/plantillas/layout.html
<!DOCTYPE html>
<html lang="es">
    <head>

        <meta charset="utf-8">
        <title>Pantalla principal</title>
        <script src="https://kit.fontawesome.com/3900b262f5.js" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'estilos/estilos.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    </head>
    <body>
        {% csrf_token %}
        <header class="encabezado">
            <div class = "logo">
                <img src="https://th.bing.com/th/id/OIP.Ngg6kQZc8l9k9tH6nyXwTAHaHa?pid=ImgDet&rs=1" alt="logo">
            </div>
            <nav class = "BotonesEncabezado" >
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href= "#" >Sesión: {{ user.username }}</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Iniciar Sesión</a></li>
                    <li><a href="{% url 'Registro' %}">Crear cuenta</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'Carrito' %}">Carrito</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Carrito</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a href= "{% url 'logout' %}">Cerrar Sesión</a></li>
                    {% endif %}
                </ul>
            </nav>     
        </header>

        <div class= "contenedor-menu">
            <nav class = "menu">
                <ul>
                    <li><a href="{% url 'Home' %}">Principal</a></li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            Categorias
                            </a>
                            <div class="dropdown-menu">
                                {% for categoria in lista_categoria %}
                                    <a class="dropdown-item" href="{% url 'FiltroCategorias' categoria.id %}">{{ categorias }}</a>
                                {% endfor %}
                            </div>
                    <li><a href="{% url 'AcercaDe' %}">Acerca de...</a></li>
                    <li><a href="mailto:matiasguzman00@hotmail.com">Contacto</a></li>
                    {% if perms.ProyectoFinal.add_producto %}
                    <li><a href="{% url 'Agregar_Producto' %}">Nuevo</a></li>
                    {% endif %}
                    {% if perms.ProyectoFinal.view_producto %}
                    <li><a href="{% url 'Lista_Producto' %}">Lista de Productos</a></li>
                    {% endif %}
                </ul>
                <form action="" method="GET" class = "d-flex" style = "max-height: 35px;">
                    <input type="text" class = "form-control" placeholder="Buscar..." name = "buscar">
                    <button type = "submit" class = "btn btn-success ">Buscar</button>
                </form>
            </nav>

        </div>

        <div class = "contenido"> 

            {% block content %}
            {%  endblock %}
            
        </div>

        <footer>
            <div class = "contenedor-footer">
                <p><b>Matías Guzmán</b></p>
                <h3>JAGUARETE KAA S.A.</h3>
                <p><b>Copyright &copy; 2021 JAGUARETE KAA S.A.</b></p> 
            </div>

        </footer>

        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% if messages %}
            {% for m in messages %}
            <script>
                Swal.fire({
                    "title": "Felicitaciones",
                    "text" : "{{m}}",
                    "icon" : "success"
                })
            </script>
            {{m}}   
            {% endfor %}
        {% endif %}
    </body>
    
</html>

Final/ProyectoFinal/templates/producto/VerProducto.html
{% extends 'plantillas/layout.html'%}

{% block content %} 
{% load humanize %}

<div class="container">
    <div class="row">
        <h1 class = "text-center">{{ producto.nombre}} </h1>
        &nbsp;
        &nbsp;
        <div class="col text-center" style="margin-top: 50px;">
            <p><img style= "max-height: 300px; min-height: 300px;" src = "{{ media_url }}{{ producto.imagen.url }}" alt = "{{ producto.imagen.name}}"></p>
        </div>
        <div class="col order-2" style = "margin-top: 60px;">

            <h2>Categoria: {{ producto.categorias}}</h2>
            <h4>Descripción: {{ producto.descripcion }}</h4>
            <h3>${{ producto.precio | intcomma}}</h3>

        </div>
    </div>
    <a href = "{% url 'carrito:Agregar' producto.id %}" class = "btn btn-success" style = "float:right">Agregar al carrito</a>
</div>
{% endblock %}

Final/ProyectoFinal/templates/producto/agregar.html
{% extends 'plantillas/layout.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="formulario">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Agregar Producto</h2>
                <br>
                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}

                    <div class="d-flex justify-content-end">
                        <a href = "{% url 'Lista_Producto' %}" class = "btn btn-secondary">Cancelar</a>
                        &nbsp;
                        <input type="submit" value="Guardar" class = "bnt btn-primary">
                    </div>
                    
                </form>
                {{ mensaje }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

Final/ProyectoFinal/templates/producto/editar.html
{% extends 'plantillas/layout.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="formulario">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Editar producto</h2>
                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}

                    <div class="d-flex justify-content-end">
                        <a href = "{% url 'Lista_Producto' %}"class = "btn btn-secondary">Cancelar</a>
                        &nbsp;
                        <input type="submit" value="Editar" class = "bnt btn-primary">
                    </div>
                    
                </form>
                {{ mensaje }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

Final/ProyectoFinal/templates/producto/lista.html
{% extends 'plantillas/layout.html' %} 

{% block content %}

{% load humanize %}
<div class="card">
    <div class="card-body">
        <div class="d-flex justify-content-center">
            <h2>Lista de Productos</h2>
        </div>
    </div>
</div>

<br>
<table class="table table-hover table-responsive-sm">
	<thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Categoria</th>
            <th>Opciones</th>
        </tr>
    </thead>

    {% for p in productos %}

    <tr>
        <td>{{ p.nombre | title }}</td>
        <td>${{ p.precio | intcomma }}</td>
        <td>{{ p.categorias | title }}</td>
        <td>
            <a href = "{% url 'Editar_Producto' p.id %}" class = "btn btn-info btn-sn">Modificar</a>
           <a href = "#" onclick = "EliminarProducto({{ p.id }})" class = "btn btn-danger btn-sn">Eliminar</a>
        </td>
    </tr>

    {% endfor %}
</table>


<script>
    function EliminarProducto(id){
        Swal.fire({
            "title" : "¿Estás seguro?",
            "text" : "Esta acción no se puede deshacer",
            "icon" : "warning",
            "showCancelButton": true,
            "cancelButtonText": "No",
            "confirmButtonText": "Si",
            "confirmButtonColor": "red",
            "cancelButtonColor": "gray",
        })
        .then(function(result){
             if(result.isConfirmed){
                window.location.href = "Eliminar/"+id+"/"
            }
        })
    }
</script>
{% endblock %}